### PR TITLE
Bump elasticsearch_dsl 0.0.9 + alternate ES hostname

### PR DESCRIPTION
**Pull request by mparent61**
@benghaziboy @MichaelButkovic 

Grab several elasticsearch_dsl fixes, including "random_score" scoring function fixes. 

http://elasticsearch-dsl.readthedocs.org/en/latest/Changelog.html

Also make it easier to use Docker-based ES for testing.

### CODE REVIEW

**Comment by benghaziboy** [comment]
Are there other things that we need to grab from more recently releases? Some of the changes are pretty seriously breaking (removal of filters) so we'll to assess anything like that upfront.

Otherwise....lgtm

**Comment by MichaelButkovic** [comment]
:+1:

**Comment by mparent61** [comment]
@benghaziboy where do you see "removal of filters" ?

**Comment by benghaziboy** [comment]
https://github.com/elastic/elasticsearch-dsl-py/blob/master/Changelog.rst

**Comment by mparent61** [comment]
@benghaziboy Agreed, though the es-dsl 2.x line is only for ES 2.0+
We're still on ES 1.4.X, so we'll be on es-dsl 0.x for the foreseeable future.

**Comment by benghaziboy** [comment]
perf

**Pull request merged**
